//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.DataAccess.Transactions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS gallery.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transactions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transactions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.DataAccess.Transactions.Resources.Transactions", typeof(Transactions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing transaction handlers&apos; actions..
        /// </summary>
        internal static string error_executing_transaction {
            get {
                return ResourceManager.GetString("error_executing_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading transactionHandler from config. Description: {0}..
        /// </summary>
        internal static string error_loading_transactionhandler {
            get {
                return ResourceManager.GetString("error_loading_transactionhandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load handlerType for typeName {0} for transactionHandler {1}..
        /// </summary>
        internal static string handlertype_cannot_be_loaded {
            get {
                return ResourceManager.GetString("handlertype_cannot_be_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context should be in one of the following states in VoteRollback - {Entered, ToBeCommitted, ToBeRollbacked}.
        /// </summary>
        internal static string invalid_context_state {
            get {
                return ResourceManager.GetString("invalid_context_state", resourceCulture);
            }
        }
    }
}
