//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CodeFactory.DataAccess {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CodeFactory.DataAccess")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="CodeFactory.DataAccess", IsNullable=false)]
    public partial class dataOperations {
        
        private dataCommand[] dataCommandsField;
        
        private dataSetAdapter[] dataSetAdaptersField;
        
        private string dataSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public dataCommand[] dataCommands {
            get {
                return this.dataCommandsField;
            }
            set {
                this.dataCommandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public dataSetAdapter[] dataSetAdapters {
            get {
                return this.dataSetAdaptersField;
            }
            set {
                this.dataSetAdaptersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class dataCommand {
        
        private string commandTextField;
        
        private replaceByParamValue[] replaceByParamValuesField;
        
        private param[] parametersField;
        
        private string nameField;
        
        private string typeField;
        
        private bool populateParametersField;
        
        private int timeoutField;
        
        public dataCommand() {
            this.populateParametersField = false;
            this.timeoutField = -1;
        }
        
        /// <remarks/>
        public string commandText {
            get {
                return this.commandTextField;
            }
            set {
                this.commandTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public replaceByParamValue[] replaceByParamValues {
            get {
                return this.replaceByParamValuesField;
            }
            set {
                this.replaceByParamValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public param[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool populateParameters {
            get {
                return this.populateParametersField;
            }
            set {
                this.populateParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class replaceByParamValue {
        
        private string oldStringField;
        
        private string newStringField;
        
        private string defaultStringField;
        
        private string paramNameField;
        
        private string paramValueField;
        
        /// <remarks/>
        public string oldString {
            get {
                return this.oldStringField;
            }
            set {
                this.oldStringField = value;
            }
        }
        
        /// <remarks/>
        public string newString {
            get {
                return this.newStringField;
            }
            set {
                this.newStringField = value;
            }
        }
        
        /// <remarks/>
        public string defaultString {
            get {
                return this.defaultStringField;
            }
            set {
                this.defaultStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string paramName {
            get {
                return this.paramNameField;
            }
            set {
                this.paramNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string paramValue {
            get {
                return this.paramValueField;
            }
            set {
                this.paramValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class columnMapping {
        
        private string sourceColumnField;
        
        private string dataSetColumnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataSetColumn {
            get {
                return this.dataSetColumnField;
            }
            set {
                this.dataSetColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class tableMapping {
        
        private columnMapping[] columnMappingsField;
        
        private string sourceTableField;
        
        private string dataSetTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public columnMapping[] columnMappings {
            get {
                return this.columnMappingsField;
            }
            set {
                this.columnMappingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceTable {
            get {
                return this.sourceTableField;
            }
            set {
                this.sourceTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataSetTable {
            get {
                return this.dataSetTableField;
            }
            set {
                this.dataSetTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class dataSetAdapter {
        
        private dataCommand selectCommandField;
        
        private dataCommand insertCommandField;
        
        private dataCommand updateCommandField;
        
        private dataCommand deleteCommandField;
        
        private tableMapping[] tableMappingsField;
        
        private string nameField;
        
        private string typeField;
        
        private bool populateCommandsField;
        
        public dataSetAdapter() {
            this.populateCommandsField = false;
        }
        
        /// <remarks/>
        public dataCommand selectCommand {
            get {
                return this.selectCommandField;
            }
            set {
                this.selectCommandField = value;
            }
        }
        
        /// <remarks/>
        public dataCommand insertCommand {
            get {
                return this.insertCommandField;
            }
            set {
                this.insertCommandField = value;
            }
        }
        
        /// <remarks/>
        public dataCommand updateCommand {
            get {
                return this.updateCommandField;
            }
            set {
                this.updateCommandField = value;
            }
        }
        
        /// <remarks/>
        public dataCommand deleteCommand {
            get {
                return this.deleteCommandField;
            }
            set {
                this.deleteCommandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public tableMapping[] tableMappings {
            get {
                return this.tableMappingsField;
            }
            set {
                this.tableMappingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool populateCommands {
            get {
                return this.populateCommandsField;
            }
            set {
                this.populateCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CodeFactory.DataAccess")]
    public partial class param {
        
        private string keyField;
        
        private string nameField;
        
        private string typeField;
        
        private string directionField;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private string sourceVersionField;
        
        private string sourceColumnField;
        
        private sbyte scaleField;
        
        private bool scaleFieldSpecified;
        
        private bool isNullableField;
        
        private bool isNullableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceVersion {
            get {
                return this.sourceVersionField;
            }
            set {
                this.sourceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scaleSpecified {
            get {
                return this.scaleFieldSpecified;
            }
            set {
                this.scaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNullableSpecified {
            get {
                return this.isNullableFieldSpecified;
            }
            set {
                this.isNullableFieldSpecified = value;
            }
        }
    }
}
