//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.ContentManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.ContentManager.Resources.WebControls", typeof(WebControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web module used for page&apos;s footer..
        /// </summary>
        internal static string FooterModule_Description {
            get {
                return ResourceManager.GetString("FooterModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Control.
        /// </summary>
        internal static string FooterModule_Title {
            get {
                return ResourceManager.GetString("FooterModule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web module used for page&apos;s header..
        /// </summary>
        internal static string HeaderModule_Description {
            get {
                return ResourceManager.GetString("HeaderModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Control.
        /// </summary>
        internal static string HeaderModule_Title {
            get {
                return ResourceManager.GetString("HeaderModule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web module which content is stored and edited by page..
        /// </summary>
        internal static string HtmlContentModule_Description {
            get {
                return ResourceManager.GetString("HtmlContentModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Content Control.
        /// </summary>
        internal static string HtmlContentModule_Title {
            get {
                return ResourceManager.GetString("HtmlContentModule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web module used for general web site navigation..
        /// </summary>
        internal static string NavigationModule_Description {
            get {
                return ResourceManager.GetString("NavigationModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Control.
        /// </summary>
        internal static string NavigationModule_Title {
            get {
                return ResourceManager.GetString("NavigationModule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web module used for publish content available through the search engine..
        /// </summary>
        internal static string PublishableContentModule_Description {
            get {
                return ResourceManager.GetString("PublishableContentModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishable Html Content Control.
        /// </summary>
        internal static string PublishableContentModule_Title {
            get {
                return ResourceManager.GetString("PublishableContentModule_Title", resourceCulture);
            }
        }
    }
}
