//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.ContentManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebParts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.ContentManager.Resources.WebParts", typeof(WebParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combintaion of pageIndex and pageSize cannot exceed the maximum value of System.Int32..
        /// </summary>
        internal static string PageIndex_PageSize_bad {
            get {
                return ResourceManager.GetString("PageIndex_PageSize_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array parameter &apos;{0}&apos; should not be empty..
        /// </summary>
        internal static string Parameter_array_empty {
            get {
                return ResourceManager.GetString("Parameter_array_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must not be empty..
        /// </summary>
        internal static string Parameter_can_not_be_empty {
            get {
                return ResourceManager.GetString("Parameter_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must not contains commas..
        /// </summary>
        internal static string Parameter_can_not_contain_comma {
            get {
                return ResourceManager.GetString("Parameter_can_not_contain_comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array &apos;{0}&apos; should not contain duplicate values..
        /// </summary>
        internal static string Parameter_duplicate_array_element {
            get {
                return ResourceManager.GetString("Parameter_duplicate_array_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        internal static string Parameter_too_long {
            get {
                return ResourceManager.GetString("Parameter_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The negative value &apos;{0}&apos; is returned when calling provider&apos;s &apos;{1}&apos; method.  The method should return non-negative integer..
        /// </summary>
        internal static string PersonalizationAdmin_UnexpectedPersonalizationProviderReturnValue {
            get {
                return ResourceManager.GetString("PersonalizationAdmin_UnexpectedPersonalizationProviderReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ApplicationName cannot exceed character length {0}..
        /// </summary>
        internal static string PersonalizationProvider_ApplicationNameExceedMaxLength {
            get {
                return ResourceManager.GetString("PersonalizationProvider_ApplicationNameExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization provider that stores data in a database..
        /// </summary>
        internal static string PersonalizationProvider_Description {
            get {
                return ResourceManager.GetString("PersonalizationProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;directoryName&apos; must be a relative path..
        /// </summary>
        internal static string PersonalizationProvider_DirectoryNameNotRelative {
            get {
                return ResourceManager.GetString("PersonalizationProvider_DirectoryNameNotRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connectionStringName attribute must be specified when registering a personalization provider..
        /// </summary>
        internal static string PersonalizationProvider_NoConnection {
            get {
                return ResourceManager.GetString("PersonalizationProvider_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute &apos;{0}&apos;, specified in the &apos;{1}&apos; personalization provider registration..
        /// </summary>
        internal static string PersonalizationProvider_UnknownProp {
            get {
                return ResourceManager.GetString("PersonalizationProvider_UnknownProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot have comma in string value &apos;{1}&apos;..
        /// </summary>
        internal static string PersonalizationProviderHelper_CannotHaveCommaInString {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_CannotHaveCommaInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot be an empty colleciton..
        /// </summary>
        internal static string PersonalizationProviderHelper_Empty_Collection {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Empty_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; must be greater than or equal to {1}..
        /// </summary>
        internal static string PersonalizationProviderHelper_Invalid_Less_Than_Parameter {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Invalid_Less_Than_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot contain more than one entry when &apos;{1}&apos; contains somes entreies..
        /// </summary>
        internal static string PersonalizationProviderHelper_More_Than_One_Path {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_More_Than_One_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input parameter cannot  be negative..
        /// </summary>
        internal static string PersonalizationProviderHelper_Negative_Integer {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Negative_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot be provided when &apos;{1}&apos; is set to &apos;{2}&apos;..
        /// </summary>
        internal static string PersonalizationProviderHelper_No_Usernames_Set_In_Shared_Scope {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_No_Usernames_Set_In_Shared_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot contain null entries..
        /// </summary>
        internal static string PersonalizationProviderHelper_Null_Entries {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Null_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot contain null or empty string entries..
        /// </summary>
        internal static string PersonalizationProviderHelper_Null_Or_Empty_String_Entries {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Null_Or_Empty_String_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed entry value &apos;{0} of input parameter &apos;{1}&apos; cannot exceed character length {2}..
        /// </summary>
        internal static string PersonalizationProviderHelper_Trimmed_Entry_Value_Exceed_Maximum_Length {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_Trimmed_Entry_Value_Exceed_Maximum_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; cannot be an empty string..
        /// </summary>
        internal static string PersonalizationProviderHelper_TrimmedEmptyString {
            get {
                return ResourceManager.GetString("PersonalizationProviderHelper_TrimmedEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; requires a database schema compatible with schema version &apos;{1}&apos;..
        /// </summary>
        internal static string Provider_Schema_Version_Not_Match {
            get {
                return ResourceManager.GetString("Provider_Schema_Version_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed string value &apos;{0}&apos; of input parameter &apos;{1}&apos; cannot exceed character length {2}..
        /// </summary>
        internal static string StringUtil_Trimmed_String_Exceed_Maximum_Length {
            get {
                return ResourceManager.GetString("StringUtil_Trimmed_String_Exceed_Maximum_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be boolean (true or false) for property &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_boolean {
            get {
                return ResourceManager.GetString("Value_must_be_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a non-negative 32-bit integer for property &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_non_negative_integer {
            get {
                return ResourceManager.GetString("Value_must_be_non_negative_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a positive 32-bit integer for property &apos;{0}&apos;..
        /// </summary>
        internal static string Value_must_be_positive_integer {
            get {
                return ResourceManager.GetString("Value_must_be_positive_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; can not be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string Value_too_big {
            get {
                return ResourceManager.GetString("Value_too_big", resourceCulture);
            }
        }
    }
}
