//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS gallery.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAccess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAccess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.DataAccess.Resources.DataAccess", typeof(DataAccess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string with name {0} was not found in the connection string section..
        /// </summary>
        internal static string connection_string_not_found {
            get {
                return ResourceManager.GetString("connection_string_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load commandBuilderType for typeName {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_commandbuildertype {
            get {
                return ResourceManager.GetString("could_not_load_commandbuildertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cound not load commandType for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_commandtype {
            get {
                return ResourceManager.GetString("could_not_load_commandtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load connectionType for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_connectiontype {
            get {
                return ResourceManager.GetString("could_not_load_connectiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load dataAdapterType for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_dataadaptertype {
            get {
                return ResourceManager.GetString("could_not_load_dataadaptertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load parameterDbType for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_parameterdbtype {
            get {
                return ResourceManager.GetString("could_not_load_parameterdbtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load parameterDbTypeProperty for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_parameterdbtypeproperty {
            get {
                return ResourceManager.GetString("could_not_load_parameterdbtypeproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load parameterType for typename {0} for provider {1}..
        /// </summary>
        internal static string could_not_load_parametertype {
            get {
                return ResourceManager.GetString("could_not_load_parametertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource does not support DataAdapters!.
        /// </summary>
        internal static string dataadapters_not_supported {
            get {
                return ResourceManager.GetString("dataadapters_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataCommand with name {0} not found..
        /// </summary>
        internal static string datacommand_not_found {
            get {
                return ResourceManager.GetString("datacommand_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data operations cache creation failed. Description: {0}..
        /// </summary>
        internal static string dataoperations_cache_loading_failed {
            get {
                return ResourceManager.GetString("dataoperations_cache_loading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataOperations validation error. Description: {0}..
        /// </summary>
        internal static string dataoperations_validation_error {
            get {
                return ResourceManager.GetString("dataoperations_validation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dataoperations file has a different datasource name than expected. Found: {0}; Expected: {1}..
        /// </summary>
        internal static string dataoperations_with_different_datasource {
            get {
                return ResourceManager.GetString("dataoperations_with_different_datasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSetAdapter with name {0} not found..
        /// </summary>
        internal static string datasetadapter_not_found {
            get {
                return ResourceManager.GetString("datasetadapter_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource with name \&quot;{0}\&quot; not found..
        /// </summary>
        internal static string datasource_not_found {
            get {
                return ResourceManager.GetString("datasource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data cache from config. Description: {0}..
        /// </summary>
        internal static string error_loading_cache_from_config {
            get {
                return ResourceManager.GetString("error_loading_cache_from_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration key collection..
        /// </summary>
        internal static string invalid_configuration_key_collection {
            get {
                return ResourceManager.GetString("invalid_configuration_key_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select command should be defined before trying to Fill a DataSet using IDataSetAdapter..
        /// </summary>
        internal static string invalid_dataset_adapter_fill {
            get {
                return ResourceManager.GetString("invalid_dataset_adapter_fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the commands Insert/Update/Delete should be defined before trying to Update a DataSet using IDataSetAdapter..
        /// </summary>
        internal static string invalid_dataset_adapter_update {
            get {
                return ResourceManager.GetString("invalid_dataset_adapter_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceByParam condition has invalid paramName = {0} (the parameter is not a member of the parameters collection)..
        /// </summary>
        internal static string invalid_replacebyparam_parameter {
            get {
                return ResourceManager.GetString("invalid_replacebyparam_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data operations config files found with mask {0}..
        /// </summary>
        internal static string no_dataoperations_config_files_found_with_mask {
            get {
                return ResourceManager.GetString("no_dataoperations_config_files_found_with_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized attribute \&quot;{0}\&quot;..
        /// </summary>
        internal static string unrecognized_attribute {
            get {
                return ResourceManager.GetString("unrecognized_attribute", resourceCulture);
            }
        }
    }
}
